# Generated by Django 5.1.5 on 2025-01-30 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Table_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Table_name', models.CharField(max_length=40)),
                ('Last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('Duration', models.CharField(default=2, max_length=3)),
                ('New_update', models.CharField(max_length=3)),
            ],
        ),
    ]
